export const CASE_STATUS_ID = {
	NEW_CASE: 'new-case',
	VALIDATED: 'validated',
	INVALID: 'invalid',
	INITIAL_CHECKS_VALIDATION: 'initial-checks-validation',
	REJECTED: 'rejected',
	INFORM_PARTIES: 'inform-parties',
	ALLOCATE_INSPECTOR: 'allocate-inspector',
	ARRANGE_EVENT: 'arrange-event',
	IN_PROGRESS: 'in-progress',
	EXCHANGE_CORRESPONDENCE: 'exchange-correspondence',
	READY_FOR_INSPECTOR: 'ready-for-inspector',
	EVENT: 'event',
	DECISION_RECOMMENDATION_ISSUED: 'decision-recommendation-issued',
	DESPATCH: 'despatch',
	FINAL_CHECK: 'final-check',
	CLOSED: 'closed',
	CANCELLED: 'cancelled',
	PAUSED_ON_HOLD: 'paused-on-hold',
	WITHDRAWN: 'withdrawn',
	IN_ABEYANCE: 'in-abeyance',
	CLOSED_OPENED_IN_ERROR: 'closed-opened-in-error'
};
