import { CONTACT_TYPE_ID } from './ids/index.ts';

export const CONTACT_TYPES = [
	{ id: CONTACT_TYPE_ID.ACQUIRING_AUTHORITY, displayName: 'Acquiring authority' },
	{ id: CONTACT_TYPE_ID.AGENT, displayName: 'Agent' },
	{ id: CONTACT_TYPE_ID.CASE_OFFICER, displayName: 'Case officer' },
	{ id: CONTACT_TYPE_ID.COMMONS_REGISTRATION_AUTHORITY, displayName: 'Commons registration authority' },
	{ id: CONTACT_TYPE_ID.CONSULTEE, displayName: 'Consultee' },
	{ id: CONTACT_TYPE_ID.GOVERNMENT_AGENCY, displayName: 'Government agency' },
	{ id: CONTACT_TYPE_ID.INTERESTED_OWNER, displayName: 'Interested owner' },
	{ id: CONTACT_TYPE_ID.INTERESTED_PERSON_PARTY, displayName: 'Interested person / party' },
	{ id: CONTACT_TYPE_ID.LANDOWNER, displayName: 'Landowner' },
	{ id: CONTACT_TYPE_ID.LANDOWNER_AGENT, displayName: 'Landowner agent' },
	{ id: CONTACT_TYPE_ID.LOCAL_PLANNING_AUTHORITY, displayName: 'Local planning authority' },
	{ id: CONTACT_TYPE_ID.LPA_AGENT, displayName: 'Local planning authority agent' },
	{ id: CONTACT_TYPE_ID.LPA_CONTACT, displayName: 'Local planning authority contact' },
	{ id: CONTACT_TYPE_ID.MEMBER_OF_PARLIAMENT, displayName: 'Member of Parliament' },
	{ id: CONTACT_TYPE_ID.NATURAL_ENGLAND, displayName: 'Natural England' },
	{ id: CONTACT_TYPE_ID.NOTIFIED_PARTY, displayName: 'Notified party' },
	{ id: CONTACT_TYPE_ID.OBJECTOR, displayName: 'Objector' },
	{ id: CONTACT_TYPE_ID.ORDER_MAKING_AUTHORITY, displayName: 'Order making authority' },
	{ id: CONTACT_TYPE_ID.ORDER_MAKING_AUTHORITY_CONTACT, displayName: 'Order making authority contact' },
	{ id: CONTACT_TYPE_ID.OTHER_PARTY, displayName: 'Other party' },
	{ id: CONTACT_TYPE_ID.POTENTIAL_CLAIMANT, displayName: 'Potential claimant' },
	{ id: CONTACT_TYPE_ID.PROGRAMME_OFFICER, displayName: 'Programme officer' },
	{ id: CONTACT_TYPE_ID.REPRESENTER, displayName: 'Representer' },
	{ id: CONTACT_TYPE_ID.REPRESENTATIVE, displayName: 'Representative' },
	{ id: CONTACT_TYPE_ID.SECRETARY_OF_STATE, displayName: 'Secretary of State' },
	{ id: CONTACT_TYPE_ID.SPONSOR, displayName: 'Sponsor' },
	{ id: CONTACT_TYPE_ID.TENANT, displayName: 'Tenant' },
	{ id: CONTACT_TYPE_ID.THIRD_PARTY, displayName: 'Third party' },
	{ id: CONTACT_TYPE_ID.APPLICANT_APPELLANT, displayName: 'Applicant/Appellant' },
	{ id: CONTACT_TYPE_ID.INSPECTOR, displayName: 'Inspector' },
	{ id: CONTACT_TYPE_ID.RELEVANT_AUTHORITY, displayName: 'Relevant authority' }
];
