import { CASE_TYPES_ID, CASE_SUBTYPES_ID } from '@pins/peas-row-commons-database/src/seed/static_data/ids/index.ts';

const TYPE_CODES: Record<string, string> = {
	[CASE_TYPES_ID.DROUGHT]: 'DRO',
	[CASE_TYPES_ID.HOUSING_PLANNING_CPOS]: 'CPO',
	[CASE_TYPES_ID.OTHER_SOS_CASEWORK]: 'SOS',
	[CASE_TYPES_ID.WAYLEAVES]: 'WAY',
	[CASE_TYPES_ID.PURCHASE_NOTICES]: 'PUR',
	[CASE_TYPES_ID.COASTAL_ACCESS]: 'MCA',
	[CASE_TYPES_ID.COMMON_LAND]: 'COM',
	[CASE_TYPES_ID.RIGHTS_OF_WAY]: 'ROW'
};

const SUBTYPE_CODES: Record<string, string> = {
	[CASE_SUBTYPES_ID.DROUGHT_ORDERS]: 'ORD',
	[CASE_SUBTYPES_ID.DROUGHT_PERMITS]: 'PER',
	[CASE_SUBTYPES_ID.DEFRA_CPO]: 'ENV',
	[CASE_SUBTYPES_ID.DESNZ_CPO]: 'ENG',
	[CASE_SUBTYPES_ID.DFT_CPO]: 'TRN',
	[CASE_SUBTYPES_ID.ADVERT]: 'ADV',
	[CASE_SUBTYPES_ID.ADHOC_CPO]: 'CPO',
	[CASE_SUBTYPES_ID.COMPLETION_NOTICE]: 'COM',
	[CASE_SUBTYPES_ID.DISCONTINUANCE_NOTICE]: 'DIS',
	[CASE_SUBTYPES_ID.MODIFICATION_TO_PP]: 'MOD',
	[CASE_SUBTYPES_ID.REVIEW_OF_MINERAL_PP]: 'MIN',
	[CASE_SUBTYPES_ID.NEW_LINES]: 'LIN',
	[CASE_SUBTYPES_ID.TREE_LOPPING]: 'TRE',
	[CASE_SUBTYPES_ID.WAYLEAVES_GENERIC]: 'WAY',
	[CASE_SUBTYPES_ID.COASTAL_ACCESS_APPEAL]: 'CAA',
	[CASE_SUBTYPES_ID.NOTICE_APPEAL]: 'NOT',
	[CASE_SUBTYPES_ID.OBJECTION]: 'OBJ',
	[CASE_SUBTYPES_ID.RESTRICTION_APPEAL]: 'RES',
	[CASE_SUBTYPES_ID.COMMONS_ECCLESIASTICAL]: 'ECC',
	[CASE_SUBTYPES_ID.COMMONS_GREATER_LONDON]: 'LDN',
	[CASE_SUBTYPES_ID.COMPULSORY_PURCHASE_CL]: 'PCL',
	[CASE_SUBTYPES_ID.CORRECTION_CL_REGISTER]: 'COR',
	[CASE_SUBTYPES_ID.DEREGISTRATION_EXCHANGE]: 'DRE',
	[CASE_SUBTYPES_ID.INCLOSURE]: 'INC',
	[CASE_SUBTYPES_ID.INCLOSURE_OBSOLESCENT]: 'OBS',
	[CASE_SUBTYPES_ID.LAND_EXCHANGE]: 'LEX',
	[CASE_SUBTYPES_ID.LOCAL_ACTS]: 'LCA',
	[CASE_SUBTYPES_ID.PUBLIC_ACCESS_LIMITATIONS]: 'PAC',
	[CASE_SUBTYPES_ID.SCHEME_OF_MANAGEMENT]: 'SOM',
	[CASE_SUBTYPES_ID.STINT_RATES]: 'STI',
	[CASE_SUBTYPES_ID.WORKS_COMMON_LAND]: 'WCL',
	[CASE_SUBTYPES_ID.WORKS_COMMON_LAND_NT]: 'WNT',
	[CASE_SUBTYPES_ID.DISPENSATION_HA80]: 'SNH',
	[CASE_SUBTYPES_ID.DISPENSATION_TCPA90]: 'SNT',
	[CASE_SUBTYPES_ID.DISPENSATION_WCA81]: 'SNW',
	[CASE_SUBTYPES_ID.OPPOSED_DMMO]: 'DMM',
	[CASE_SUBTYPES_ID.OPPOSED_PPO_HA80]: 'PPH',
	[CASE_SUBTYPES_ID.OPPOSED_PPO_TCPA90]: 'PPT',
	[CASE_SUBTYPES_ID.SCHEDULE_14_APPEAL]: 'S14A',
	[CASE_SUBTYPES_ID.SCHEDULE_14_DIRECTION]: 'S14D',
	[CASE_SUBTYPES_ID.SCHEDULE_13A_APPEAL]: 'S13A',
	[CASE_SUBTYPES_ID.HOUSING]: 'HOU',
	[CASE_SUBTYPES_ID.PLANNING_SUB]: 'PLA',
	[CASE_SUBTYPES_ID.ADHOC]: 'ADH',
	[CASE_SUBTYPES_ID.REVOCATION]: 'REV',
	other: 'OTH'
};

/**
 * Builds reference prefix based on type + subtype.
 * Some (few) types have no subtype
 */
export function buildReferencePrefix(typeId: string | null, subtypeId: string | null): string {
	const typeCode = typeId ? TYPE_CODES[typeId] : 'UNK';

	if (subtypeId && SUBTYPE_CODES[subtypeId]) {
		return `${typeCode}/${SUBTYPE_CODES[subtypeId]}/`;
	}

	return `${typeCode}/`;
}
